--!strict
-- A radio that plays through all players.

-- burn 90935264615216
-- birds ambiance 9119383684

-- jazz rush 1839444520
-- jazz okish 1842179755
-- jazz slow pace 115033751770984

-- jazz holy ballz 1839019142
-- jazz HOLY CORN BALLZ 85957213099262
-- jazz corn ball 112017289458628

-- jazz ONG WTF TS CRUISE 89362925357564
-- jazz another from SoulNectar 94175871924822
-- jazz SoulNectar 97645306300098
-- jazz SoulNectar 135106210449794

-- jazz chase okish 1839336610

-- soundIds = {94175871924822}
-- cursor = 1

-- sound = Instance.new("Sound")
-- sound.Name = "Background"
-- sound.Parent = workspace.Invisible.SFX

-- sound.SoundId = "rbxassetid://" .. soundIds[cursor]
-- sound:Play()

-- sound.Ended:Connect(function(_soundId)
--     cursor = (cursor % #soundIds) + 1

--     sound.SoundId = "rbxassetid://" .. soundIds[cursor]
--     sound:Play()
-- end)
